#!/bin/bash

mkdir -p ~/.nvim/backup
mkdir -p ~/.nvim/swap

[ ! -L /usr/share/nvim/site ] && ln -s /etc/nvim /usr/share/nvim/site
[ -f /etc/xdg/nvim/sysinit.vim ] && sed -i 's|^source .*.vim$|source /etc/nvim/init.vim|g' /etc/xdg/nvim/sysinit.vim
